# Generated by Django 5.1.6 on 2025-02-27 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('date_distribution', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_main_list_size', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validite', models.DateField(auto_now_add=True)),
                ('code_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('heure_utilise', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
