# Generated by Django 5.1.6 on 2025-02-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution_management', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_location', to='user_management.location'),
        ),
        migrations.AddField(
            model_name='distributionlist',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_location', to='user_management.location'),
        ),
        migrations.AddField(
            model_name='distributionlist',
            name='main_list',
            field=models.ManyToManyField(blank=True, related_name='main_list', to='user_management.beneficiaire'),
        ),
        migrations.AddField(
            model_name='distributionlist',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='waiting_list', to='user_management.beneficiaire'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='distribution_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution_management.distributionlist'),
        ),
        migrations.AddField(
            model_name='qrcodedistribution',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.beneficiaire'),
        ),
    ]
