# Generated by Django 5.1.6 on 2025-02-27 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='is_first_loggin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='num_telephone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être valide (ex. +33 1 23 45 67 89 ou 0123456789).', regex='^\\+?(\\d[\\d\\s\\-]*){10,20}$')]),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='num_telephone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être valide (ex. +33 1 23 45 67 89 ou 0123456789).', regex='^\\+?(\\d[\\d\\s\\-]*){10,20}$')]),
        ),
    ]
